name: build-artifacts
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies (Linux)
        run: sudo apt-get update && sudo apt-get install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev pkg-config
        if: matrix.os == 'ubuntu-latest'

      - uses: lukka/get-cmake@v3.31.6

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5

      - name: Run CMake and install necessary packages
        uses: lukka/run-cmake@v10.7
        if: matrix.os != 'macos-latest'
        with:
          configurePreset: 'x64-Release'
          buildPreset: 'x64-Release'

      - name: Install lipomerge (macOS)
        if: matrix.os == 'macos-latest'
        run: pipx install lipomerge

      - name: Install packages (arm64) (macOS)
        if: matrix.os == 'macos-latest'
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
        env:
          VCPKG_DEFAULT_TRIPLET: arm64-osx

      - name: Install packages (x64) (macOS)
        if: matrix.os == 'macos-latest'
        uses: lukka/run-vcpkg@v11.5
        with:
          runVcpkgInstall: true
        env:
          VCPKG_DEFAULT_TRIPLET: x64-osx
          VCPKG_INSTALLED_DIR: vcpkg_installed/tmp

      - name: Merge packages into universal libraries (macOS)
        if: matrix.os == 'macos-latest'
        run: lipomerge vcpkg_installed/arm64-osx vcpkg_installed/tmp/x64-osx vcpkg_installed/uni-osx

      - name: Run CMake (macOS)
        uses: lukka/run-cmake@v10.7
        if: matrix.os == 'macos-latest'
        with:
          configurePreset: 'uni-osx-Release'
          buildPreset: 'uni-osx-Release'

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: sayaslicer-linux
          path: |
            out/build/x64-Release/sayaslicer/sayaslicer
            out/build/x64-Release/sayaslicer/lang/

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'windows-latest'
        with:
          name: sayaslicer-windows
          path: |
            out/build/x64-Release/sayaslicer/*.dll
            out/build/x64-Release/sayaslicer/*.exe
            out/build/x64-Release/sayaslicer/lang/

      - name: Tar files (macOS)
        if: matrix.os == 'macos-latest'
        run: tar -C out/build/uni-osx-Release/sayaslicer/ -cvf sayaslicer.tar sayaslicer.app

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'macos-latest'
        with:
          name: sayaslicer-osx.tar
          path: |
            sayaslicer.tar
